# Generated by Django 2.0.3 on 2018-05-21 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0013_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comporisoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comporisoon', to='mainApp.Product')),
            ],
        ),
    ]
