# Generated by Django 2.0.3 on 2018-05-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180518_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Product')),
            ],
        ),
    ]
