# Generated by Django 2.0.3 on 2018-05-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslider',
            name='image',
            field=models.FileField(upload_to='BannerSlider'),
        ),
    ]
