# Generated by Django 2.0.3 on 2018-05-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_speacialdeal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='mainApp.Product'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='mainApp.Category'),
        ),
    ]
