# Generated by Django 2.0.3 on 2018-05-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomarRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password_1', models.CharField(max_length=30, verbose_name='Password')),
                ('password_2', models.CharField(max_length=30, verbose_name='Password 2')),
            ],
        ),
    ]
