# Generated by Django 2.0.3 on 2018-05-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
