# Generated by Django 2.0.3 on 2018-05-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0002_cartlist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='quantity',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
